# Generated by Django 5.0.4 on 2024-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_categoria_cliente_equipo_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio_promocion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="producto",
            name="promocion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(upload_to="uploads/producto/"),
        ),
    ]
