# Generated by Django 5.0.4 on 2024-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_producto_precio_promocion_producto_promocion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="uploads/liga/"),
                ),
            ],
        ),
    ]
