# Generated by Django 5.0.4 on 2024-04-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_equipo_liga"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="liga",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.liga"
            ),
        ),
    ]
