# Generated by Django 5.0.4 on 2024-04-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_producto_liga"),
    ]

    operations = [
        migrations.AddField(
            model_name="liga",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.categoria",
            ),
        ),
    ]
