# Generated by Django 5.0.4 on 2024-05-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_jugadores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jugadores",
            name="equipo",
        ),
    ]
