# Generated by Django 5.0.4 on 2024-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_jugadores_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jugadores",
            name="liga",
        ),
    ]
