# Generated by Django 5.0.4 on 2024-05-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_remove_jugadores_liga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="equipo",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="liga",
        ),
        migrations.CreateModel(
            name="Publicidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/publicidad/"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.categoria",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Orden",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
