# Generated by Django 5.0.4 on 2024-05-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_orden_cliente_remove_orden_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicidad",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/publicidades/"
            ),
        ),
    ]
