# Generated by Django 5.0.4 on 2024-05-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_publicidad_imagen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicidad",
            old_name="imagen",
            new_name="logo",
        ),
    ]
