# Generated by Django 5.0.4 on 2024-05-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_rename_imagen_publicidad_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicidad",
            old_name="logo",
            new_name="imagen",
        ),
    ]
